config/routes.rb
ReportCard::Application.routes.draw do
  devise_for :users
  devise_for :admins

 root :to => "home#index"
 match 'general' => 'students#general', :as => :general
 match 'attendance' => 'students#attendance', :as => :attendance
 match 'grades' => 'students#grades', :as => :grades
 match 'tests' => 'students#tests', :as => :tests
 match 'comments' => 'students#comments', :as => :comments
 match 'send_comments' => 'students#send_comments', :as => :send_comments
 match 'save_comment' => 'students#save_comment', :as => :save_comment
 
 match 'done' => 'students#done', :as => :done

end

app/models/admin.rb
class Admin < ActiveRecord::Base
  devise :database_authenticatable, :trackable, :timeoutable, :lockable
end

app/models/anomaly.rb
class Anomaly < ActiveRecord::Base
  belongs_to :attendance
end

app/models/assessment.rb
class Assessment < ActiveRecord::Base
  belongs_to :standard
  belongs_to :student
  acts_as_taggable_on :comment
end

app/models/attendance.rb
class Attendance < ActiveRecord::Base
  acts_as_taggable_on :comment
  belongs_to :student

  has_many :anomalies
  def lates_by_month(month)
    anomalies.select {|a| a.kind == "late" && a.school_date.month == month }
  end
  def lates
    anomalies.select {|a| a.kind == "late" }
  end
  def absences
    anomalies.select {|a| a.kind == "absent"}
  end
end

app/models/exam.rb
class Exam < ActiveRecord::Base
  has_many :exam_assessments
end

app/models/exam_assessment.rb
class ExamAssessment < ActiveRecord::Base
  belongs_to :exam
  has_many :sections
  belongs_to :student
  acts_as_taggable_on :comment
end

app/models/section.rb
class Section < ActiveRecord::Base
  belongs_to :assessment
  belongs_to :exam_assessment
end

app/models/standard.rb
class Standard < ActiveRecord::Base
  belongs_to :subject
  has_many :assessments
end

app/models/student.rb
class Student < ActiveRecord::Base
  acts_as_taggable_on :comment
  belongs_to :user
  has_many :assessments
  has_many :exam_assessments
  has_many :attendances

  def self.delete_all_comments
    ActsAsTaggableOn::Tag.all.each do |t| t.delete end
  end
  def first_name
    name.split(" ").first
  end
  def last_name
    name.split(" ").last
  end

end

app/models/subject.rb
class Subject < ActiveRecord::Base
  has_many :standards
end

app/models/user.rb
class User < ActiveRecord::Base
  acts_as_tagger
  has_one :student
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me
  def name
    student.name
  end
  def first_name
    student.first_name
  end
  def last_name
    student.last_name
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/home_controller.rb
class HomeController < ApplicationController 
  def index
    if signed_in?
      redirect_to general_path
    end
  end
end

app/controllers/students_controller.rb
class StudentsController < ApplicationController 
  def general
    if current_admin
      @admin = true
      @student_to_view = params[:student_to_view] 
      if @student_to_view 
        session[:student_to_view] = @student_to_view
      else
        session[:student_to_view] = Student.first
      end
      @student = Student.find(session[:student_to_view])
    end
    @student ||= current_user.student 
  end
  def index
  end

  def attendance
    if current_admin
      @admin = true
      @student_to_view = params[:student_to_view] 
      if @student_to_view 
        session[:student_to_view] = @student_to_view
      else
        session[:student_to_view] = Student.first
      end
      @student = Student.find(session[:student_to_view])
    end
    @student ||= current_user.student
    @attendances = Attendance.find_all_by_student_id(@student.id)
  end

  def grades
    if current_admin
      @admin = true
      @student_to_view = params[:student_to_view] 
      if @student_to_view 
        session[:student_to_view] = @student_to_view
      else
        session[:student_to_view] = Student.first
      end
      @student = Student.find(session[:student_to_view])
    end
    @subjects = Subject.all
    @student ||= current_user.student 
  end

  def tests
    if current_admin
      @admin = true
      @student_to_view = params[:student_to_view] 
      if @student_to_view 
        session[:student_to_view] = @student_to_view
      else
        session[:student_to_view] = Student.first
      end
      @student = Student.find(session[:student_to_view])
    end
    @student ||= current_user.student 
    @exams = Exam.all
  end

  def comments
    if current_admin
      @admin = true
      @student_to_view = params[:student_to_view] 
      if @student_to_view 
        session[:student_to_view] = @student_to_view
      else
        session[:student_to_view] = Student.first
      end
      @student = Student.find(session[:student_to_view])
    end
    @student ||= current_user.student 
  end

  def send_comments
    #if TeacherMailer.comments_email(params[:comment], params[:student], params[:email], params[:phone]).deliver
      #current_user.update_attribute(:comments_sent, true)
    
   Student.delete_all_comments
   redirect_to done_path
   # else
      #redirect_to comments_path
   # end
    #TeacherMailer.comments_email(@user).deliver
  end

  def save_comment
    if params[:model] == "student"
      o = current_user.student
    elsif params[:model] == "exam_assessment"
      o = ExamAssessment.find(params[:object_id])
    elsif params[:model] == "assessment"
      o = Assessment.find(params[:object_id])
    elsif params[:model] == "attendance"
      o = Attendance.find(params[:object_id])
    end
    o.comment_list = [params[:comment]]
    if o.save
      flash[:notice] = "Your comment has been saved!" 
      redirect_to :back
    else
      flash[:alert] = "Something went wrong..." 
      redirect_to :back
    end
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/admins/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>

app/views/home/index.html.erb
<div>
  <h2> Welcome to the virtual report card! </h2>

  <div class="span-14">
    <% form_for("user", :url => user_session_path) do |f| %>
      <fieldset> 
        <legend>Sign in</legend>
        <%= f.label :email %> <br />
        <%= f.text_field :email %> <br />
        <%= f.label :password %> <br />
        <%= f.password_field :password %> <br />
        <%= f.submit 'Sign in' %> 
      </fieldset>
    <% end %>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>ReportCard</title>
  <%= stylesheet_link_tag "main" %>
  <%= stylesheet_link_tag "screen", :media => "screen, projection" %>
  <%= stylesheet_link_tag "print", :media => "print" %>
<!--[if IE]>
<%= stylesheet_link_tag "ie", :media=>"screen, projection" %>
<![endif]-->

  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
  
</head>
<body>
  <div id="container">
    <%- flash.each do |key, msg| -%>
      <div id="<%= key %>" class="flash">
        <p><%= msg %></p>
        <div class="clear"></div>
      </div>
    <%- end -%>
    <%= yield %>
  </div>
</body>
</html>

app/views/layouts/home.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReportCard</title>
    <%= stylesheet_link_tag "main" %>
    <%= stylesheet_link_tag "screen", :media => "screen, projection" %>
    <%= stylesheet_link_tag "fullcalendar", :media => "screen, projection" %>
    <%= stylesheet_link_tag "print", :media => "print" %>
    <%= stylesheet_link_tag "fullcalendar.print", :media => "print" %>
    <!--[if IE]>
    <%= stylesheet_link_tag "ie", :media=>"screen, projection" %>
    <![endif]-->

    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js" %>
    <%= javascript_include_tag 'rails' %>
    <%= javascript_include_tag "fitted" %>
    <%= javascript_include_tag "application" %>

    <%= javascript_include_tag "jquery-ui-1.8.11.custom.min" %>
    <%= javascript_include_tag "fullcalendar.min" %>
    <%= csrf_meta_tag %>

  </head>
  <body>
    <div id="header-background">
      <div id="header-background-child">
      </div> 
    </div>
    <div id="container">
      <div id="header" class="span-24">
        <h1 id="login-title" class="span-11">Report Card</h1>
        <div id="sign-in" class="span-1">
        </div>

      </div>

      <div class="span-24" id="content-wrapper">

        <div id="content">
          <%= yield %>
        </div>

      </div>
    </div>
  </body>
</html>

app/views/layouts/students.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ReportCard</title>
    <%= stylesheet_link_tag "main" %>
    <%= stylesheet_link_tag "screen", :media => "screen, projection" %>
    <%= stylesheet_link_tag "fullcalendar", :media => "screen, projection" %>
    <%= stylesheet_link_tag "print", :media => "print" %>
    <%= stylesheet_link_tag "fullcalendar.print", :media => "print" %>
    <!--[if IE]>
    <%= stylesheet_link_tag "ie", :media=>"screen, projection" %>
    <![endif]-->

    <%= javascript_include_tag "http://ajax.googleapis.com/ajax/libs/jquery/1.4.1/jquery.min.js" %>
    <%= javascript_include_tag 'rails' %>
    <%= javascript_include_tag "fitted" %>
    <%= javascript_include_tag "application" %>

    <%= javascript_include_tag "jquery-ui-1.8.11.custom.min" %>
    <%= javascript_include_tag "fullcalendar.min" %>
    <%= javascript_include_tag "main" %>
    <%= javascript_include_tag "placeholder" %>
    <%= csrf_meta_tag %>

  </head>
  <body>
    <div id="header-background">
      <div id="header-background-child">
      </div> 
    </div>
    <div id="container">
      <%= render :partial => "header" %>

      <div class="span-24" id="content-wrapper">

        <div id="content">
          <%= render :partial => "notice_div.html.erb" %>
          <%= yield %>
        </div>

      </div>
    </div>

    <div id="footer-background">
    </div>
  </body>
</html>

app/views/students/_attendance_comment_box.html.erb
<div class="column span-7 attendance-comment">
  <% form_tag(save_comment_path, :remote => true, :name => "comment #{attendance.id}") do %>
    <% if attendance.comment_list.blank? %>
      <%= text_area_tag "comment", "", :placeholder => "Write comments or questions here"  %>
    <% else %>
      <%= text_area_tag "comment", attendance.comment_list.first %>
    <% end %>
    <%= hidden_field_tag "model", "attendance" %>
    <%= hidden_field_tag "object_id", attendance.id %>
    <div class="submit-button">
      <% unless @admin %>
        <%= submit_tag "Save Comment" %>
      <% end %>
    </div>
  <% end %>
</div>

app/views/students/_calendar.html.erb
<% month = attendance.month %>
<div class="column span-3 clear">
</div>
<div class="calendar <%= month %> span-9">
  <script type="text/javascript">
    $(document).ready(function() {

        var m = <%= month %>;

        <% if attendance.anomalies.present? %>
          var anomalyString = '<%= attendance.anomalies.to_json.html_safe %>';
          var anomalies = eval(anomalyString);

          var theEvents = [];
          for (var i = 0; i < anomalies.length; i++) {
          anomalyDescription = anomalies[i]['anomaly']['kind'];
          anomalyDay = anomalies[i]['anomaly']['school_date'].split('-')[2];
          anomalyMonth = parseInt(anomalies[i]['anomaly']['school_date'].split('-')[1]) - 1;
          anomalyYear = anomalies[i]['anomaly']['school_date'].split('-')[0];

          var theEvent = {
            title: anomalyDescription,
            start: new Date(anomalyYear, anomalyMonth, anomalyDay),
            allDay: true
            };
            theEvents.push(theEvent);
          };

        <% else %>
          theEvents = [{}];
        <% end %>

        $('.<%= month %>').fullCalendar({
          year: 2011,
          month: m,
          date: 1,
          weekends: false,
          weekMode: 'liquid',
          editable: false,
          eventColor: '#FEFA95',
          eventTextColor: 'black',
          header : {
          center:   '',
          right:   '',
          left: 'title',
          },
          events: theEvents
        });
    });
</script>
  </div>

app/views/students/_header.html.erb
<div id="header" class="span-24 last">
  <h2 id="title" class="span-5">Report Card</h2>
  <div id="sign-in" class="span-19 last">
    <% if user_signed_in? %>
      <span class="user-name">
        <%= current_user.name %>
      </span>
      <%= link_to "logout", destroy_user_session_path, :class => "link" %>


    <% elsif admin_signed_in? %>

      <% @students = Student.all %>
      Select Student: 
      <%= select_tag "student_viewing", options_from_collection_for_select(@students, "id", "name", session[:student_to_view]) %>











    <% else %>
      <%= link_to "login", new_user_session_path, :class => "link" %>
    <% end %>
  </div>
  <div class="span-15 clear">
    <%= render :partial => "nav" %>
  </div>
</div>

app/views/students/_month_summary.html.erb
  <div class="month">
    <% absences = attendance.absences %>
    <% @lates = attendance.lates_by_month(attendance.month + 1) %>
    <div class="column span-5 attendance-description text-box">
      <h3 class="list-heading">Summary:</h3>
      <hr / class="shallow-bottom">
      <div>
        Total days absent: <%= absences.count %>
    </div>
    <div>
      Total days late: <%= @lates.count %>
  </div>
  <br />
  <br />
  <% if attendance.anomalies.present? %>
    <h3 class="list-heading">Details:</h3>
    <hr / class="shallow-bottom">
    <% absences.each do |a| %>
      <div>
        <%= "Absent: #{a.school_date.month}/#{a.school_date.day}" %>
      </div>
    <% end %>
    <% @lates.each do |l| %>
      <div>
        <% time = l.moment.hour - 4 %>
        <% ampm = time < 12 ? "AM" : "PM" %>
        <%= "Late (#{time} #{ampm}): #{l.school_date.month}/#{l.school_date.day}" %>
      </div>
    <% end %>

  <% end %>

</div>
</div>

app/views/students/_nav.html.erb
<% pages = ["general", "attendance", "grades", "tests", "comments"] %>
  <ul id="navigation" class="">
      <% pages.each do |page| %>
        <% if page == params[:action] %>
          <li class="clickable active" id="<%="#{page}"%>-link">
            <% if @admin %>
              <%= link_to page.capitalize, "#{page}#{params[:student_to_view].present? ? '?student_to_view='+params[:student_to_view] : ''}" %>
            <% else %>
              <%= link_to page.capitalize, "#{page}" %>
            <% end %>
          </li>
        <% else %>
          <li class="clickable" id="<%="#{page}"%>-link">
            <% if @admin %>
              <%= link_to page.capitalize, "#{page}#{params[:student_to_view].present? ? '?student_to_view='+params[:student_to_view] : ''}" %>
            <% else %>
              <%= link_to page.capitalize, "#{page}" %>
            <% end %>
          </li>
        <% end %>
      <% end %>
  </ul>

app/views/students/_notice_div.html.erb
<%- flash.each do |key, msg| -%>
  <div id="<%= key %>" class="flash">
    <p><%= msg %></p>
    <div class="clear"></div>
  </div>
<%- end -%>

app/views/students/attendance.html.erb
<h2 class="shallow-bottom span-14 heading">Attendance</h2>
<div id="absence-summary" class="span-3 last">
  <div class="span-3">
    Total absences: <%= Attendance.where(:student_id => @student.id).map{|a| a.absences}.flatten.count %>
</div>
<div class="span-3">
  Total days late: <%= Attendance.where(:student_id => @student.id).map{|a| a.lates}.flatten.count %>
  </div>
</div>


<hr />
<% @attendances.each do |attendance| %>
  <div class="span-15">
    <%= render :partial => "calendar", :locals => {:attendance => attendance} %>
    <%= render :partial => "month_summary", :locals => {:attendance => attendance} %>
  </div>
    <%= render :partial => "attendance_comment_box", :locals => {:attendance => attendance} %>
<% end %>

app/views/students/comments.html.erb
<h2 class="shallow-bottom heading"> Your Comments </h2>
<hr />
<div class="comment-summary">
    <% if @student.comment_list.first.present? %>
      <div class="span-7 text-box">
            <b>General:</b>
            <span class="comment-category">General</span>
            <hr class="shallow-bottom" />

            <div> "<%= @student.comment_list.first %>" </div>
      </div>
    <% end %>
    <% Attendance.where(:student_id => @student.id).each do |a| %>
            <% if a.comment_list.first.present? %>
              <div class="span-7 text-box">
                <b> Month <%= a.month %>: </b>
                <span class="comment-category">Attendance</span>
                <hr class="shallow-bottom" />

                <div>"<%= a.comment_list.first %>"</div>
              </div>
            <% end %>
        <% end %>
        <% @student.assessments.each do |a| %>
            <% if a.comment_list.first.present? %>
              <div class="span-7 text-box">
                <b><%= a.standard.subject.description %>:</b>
                <span class="comment-category">Grades</span>
                  <hr class="shallow-bottom" />

                <div>"<%= a.comment_list.first %>"</div>
              </div>
            <% end %>
        <% end %>
      <% @student.exam_assessments.each do |e| %>
          <% if e.comment_list.first.present?  %>
            <div class="span-7 text-box">
              <b><%= e.exam.kind %>:</b>
              <span class="comment-category">Tests</span>
                <hr class="shallow-bottom" />

              <div>"<%= e.comment_list.first %>"</div>
            </div>
          <% end %>
      <% end %>

</div>
<br / class="clear">


<% unless @admin %>
  <div class="clear sent-comments <%=current_user.comments_sent?%>">
      <a href="#">
        <h2 id="add-more-comments">Your comments have been sent! <br /><span class="small-text">(If you forgot something, click here to send additional comments)</span> </h2>
      </a>
    </div>

  <br />
  <div id="send-comments" class="clear <%= !current_user.comments_sent?%>">
    <% form_tag(send_comments_path, :remote => true, :name => "comment #{@student.id}") do %>
      <fieldset>
        <legend> Email Your Comments to Mr. Wairi</legend>
        <%= text_area_tag "comment", "", :placeholder => "Final questions or feedback for Mr. Wairi?", :class => "span-3", :id => "final-comment" %>
        <div id="contact-info" class="span-15">
          How would you like Mr. Wairi to get back to you?<br />
          <%= text_field_tag "phone", "", :placeholder => "enter your phone #" %> 
          <%= text_field_tag "email", "", :placeholder => "enter your email address" %> <br />
        </div>
        <%= hidden_field_tag "student", @student.name %>
        <div id="submit-comments-button" class="submit-comments">
          <%= submit_tag "Email Mr. Wairi These Comments" %>
        </div>
      </fieldset>
    <% end %>
  </div>
<% end %>

app/views/students/done.html.erb
<div class="clear sent-comments">
  <h2 id="add-more-comments">Your comments have been sent!</h2>
</div>

app/views/students/general.html.erb
<div>
  <div id="intro-text" class="span-15">
    <b>Welcome to <%= @student.first_name %>'s report card! </b>
      <hr / class="shallow-bottom">
   Here, you can look at <%= @student.first_name %>'s basic academic performance and attendance record.  Want to leave comments for Mr. Wairi? Click "send" on the last page.  (All the comments that you have written will be emailed to Mr. Wairi.) Use the tabs at the top of the screen to view other pages! 

  </div>
  <div class="span-15" id="notes-from-teacher">
    <span class="teacher-image">
      <%= image_tag "josh.png", :class => "span-4" %>
    </span>

    <div class="text-box">
      <h4 class="span-10">
        <b> Here's what Mr. Wairi has to say about <%= @student.first_name %>'s performance this term: </b>
      </h4>
       <ul>
         "<%= @student.performance_summary %>"
       </ul>
    </div>
  </div>
  <div class="prepend-1 span-7">
    <%= form_tag(save_comment_path, :remote => true) %>
    <% if @student.comment_list.blank? %>
      <%= text_area_tag "comment", "", :placeholder => "Write comments or questions here" %>
    <% else %>
      <%= text_area_tag "comment", @student.comment_list.first %>
    <% end %>
    <%= hidden_field_tag "model", "student" %>
    <div class="submit-button">
      <% unless @admin %>
        <%= submit_tag "Save Comment" %>
      <% end %>
    </div>
  </div>
</div>

app/views/students/grades.html.erb
<h2 class="span-16 heading"> Academic Performance </h2>
<% possible_scores = {'m' => "Meets the standard consistently", 's' => "Sometimes meets the standard", 'n' => "Not meeting the standard", 'na' => "Standard not assessed this term"} %>
<% abbreviations = ['m', 's', 'n', 'na'] %>

<div id="standards-explanation" class="span-6">
  <% abbreviations.each do |a| %>
    <div class="<%="grade-#{a}"%>"> <span class="metric"><%= a %> </span> - <%= possible_scores[a] %> </div>
  <% end %>
  
</div>
<hr />

  <% @subjects.each do |subject| %>
  <div class="span-24 subject">
      <div class="subject-title">
        <%= subject.description %>
      </div>
    <table class= "subject-details span-15 scores">
        <tr>
          <th>Grading Period </th>
          <th>1 </th>
          <th>2 </th>
          <th>3 </th>
          <th>4 </th>
        </tr>
        <% subject.standards.each do |standard| %>
          <tr class="metrics-and-scores border">
              <td class="grade-description">
                 <%= standard.description.html_safe %>
               </td>
               <% standard.assessments.where(:student_id => @student.id).each do |a| %>
                 <td class="grade grade-<%= a.score %>">
                   <%= a.score %>
                 </td>
               <% end %>
          </tr>
        <% end %>
    </table>
    <div class="prepend-1 span-7">
      <% form_tag(save_comment_path, :remote => true, :name => "comment #{subject.id}") do %>
        <% @assessment = subject.standards.first.assessments.where(:student_id => @student.id).first %>
        <% if @assessment.comment_list.blank? %>
          <%= text_area_tag "comment", "", :placeholder => "Write comments or questions here" %>
        <% else %>
          <%= text_area_tag "comment", @assessment.comment_list.first %>
        <% end %>
        <%= hidden_field_tag "model", "assessment" %>
        <%= hidden_field_tag "object_id", @assessment.id %>
        <div class="submit-button">
          <% unless @admin %>
            <%= submit_tag "Save Comment" %>
          <% end %>
        </div>
      <% end %>
    </div>
  </div>
  <% end %>

app/views/students/index.html.erb
<br />
<div>
  <h2> Welcome to Joe's report card! </h2>
  <div id="intro-text">
    <p> Here, you can look at Jose's basic academic performance and attendance record.  Want to leave comments for Mr. Wairi? Click "send" on the last page.  (All the comments that you have written will be emailed to Mr. Wairi.) Use the highlighted arrows at the bottom of the screen to see another page!  </p>

  </div>
  <div class="span-15 prepend-4">
    <%= image_tag "josh.png", :class => "span-4" %>
    <h4 class="span-10">
      Here's what Mr. Wairi has to say about Joe's performance this term:
    </h4>

    <div id="notes-from-josh">
       <p>
         Lorem ipsum dolor sit amet, consectetur magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.  Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum
       </p>
    </div>
  </div>
</div>

app/views/students/tests.html.erb
<h2 class="span-16 heading shallow-bottom"> Tests </h2>
<% possible_scores = {'m' => "High Scoring", 's' => "Medium Scoring", 'n' => "Low scoring", 'na' => "Test not taken"} %>


<hr />
  <% @exams.each do |exam| %>
    <% @exam = exam %>
  <div class="span-24 subject">
      <div class="subject-title">
        <%= @exam.kind %>
      </div>
      <table class= "exam-details span-15 scores">
        <th>
          Period
        </th>
        <% @exam.exam_assessments.where(:student_id => @student.id).map { |ea| ea.sections}.flatten.map {|s| s.name }.uniq.each do |section| %>
        <th>
          <%= section %>
        </th>
        <% end %>
        <% @exam.exam_assessments.where(:student_id => @student.id).each do |ea|  %>
          <tr>
            <td>
              <%= Time.local(ea.period.year, ea.period.month).strftime('%b  %Y') %>
            </td>
          <% ea.sections.each do |s| %>
            <td>
              <%= s.score %>
            </td>
          <% end %>
          </tr>
        <% end %>
      </table>
    <div class="prepend-1 span-7">
      <% form_tag(save_comment_path, :remote => true) do %>
        <% @exam_assessment = exam.exam_assessments.where(:student_id => @student.id).first %>
        <% if @exam_assessment.comment_list.blank? %>
          <%= text_area_tag "comment", "", :placeholder => "Write comments or questions here" %>
        <% else %>
          <%= text_area_tag "comment", @exam_assessment.comment_list.first %>
        <% end %>
        <%= hidden_field_tag "model", "exam_assessment" %>
        <%= hidden_field_tag "object_id", @exam_assessment.id %>
        <div class="submit-button">
          <% unless @admin %>
            <%= submit_tag "Save Comment" %>
          <% end %>
        </div>
      <% end %>
    </div>

  </div>
  <% end %>

app/views/users/shared/_links.erb
<%- if controller_name != 'sessions' %>
  <%= link_to "Sign in", new_session_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.registerable? && controller_name != 'registrations' %>
  <%= link_to "Sign up", new_registration_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.recoverable? && controller_name != 'passwords' %>
  <%= link_to "Forgot your password?", new_password_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.confirmable? && controller_name != 'confirmations' %>
  <%= link_to "Didn't receive confirmation instructions?", new_confirmation_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.lockable? && resource_class.unlock_strategy_enabled?(:email) && controller_name != 'unlocks' %>
  <%= link_to "Didn't receive unlock instructions?", new_unlock_path(resource_name) %><br />
<% end -%>

<%- if devise_mapping.omniauthable? %>
  <%- resource_class.omniauth_providers.each do |provider| %>
    <%= link_to "Sign in with #{provider.to_s.titleize}", omniauth_authorize_path(resource_name, provider) %><br />
  <% end -%>
<% end -%>